version: "3.3"

services:
  db: 
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}

  wordpress: 
    image: wordpress:${WP_VERSION}
    ports:
      - ${PORT}:80
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_HOST=db
    volumes:
      - ./src/:/var/www/html/
      
  frontend:
    image: spellbook_ug_frontend-frontend
    container_name: frontend
    ports: 
      - ${FRONTEND_PORT}:${FRONTEND_PORT}