version: "3.3"

# used for pipeline build
services:
  db: 
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${WORDPRESS_DB_PORT}:${WORDPRESS_DB_PORT}
    environment:
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      # - MYSQL_USER=${WORDPRESS_DB_USER}
      # - MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_PASSWORD}
      # - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h db
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 10
      
  wordpress:
    image: flobbe9/${NAME}
    depends_on: 
      db: 
        condition: service_healthy
    build: 
      context: .
      args:
        - WORDPRESS_VERSION=${WORDPRESS_VERSION}
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    ports: 
      - ${PORT}:80