# used for dev
services:
  db: 
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${WORDPRESS_DB_PORT}:${WORDPRESS_DB_PORT}
    environment:
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./dbVolume/:/var/lib/mysql/
    healthcheck:
      test: mysqladmin ping -h db
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 10

  wordpress: 
    # image: wordpress:${WORDPRESS_VERSION}
    image: dev_${NAME}
    depends_on: 
      db: 
        condition: service_healthy
    build: 
      context: .
      args:
        - WORDPRESS_VERSION=${WORDPRESS_VERSION}
    environment:
        - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
        - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
        - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
        - WORDPRESS_DB_HOST=db
    ports:
      - 8080:80
    volumes:
      - ./src/wp-content/:/var/www/html/wp-content/
      - ./src/wp-config.php:/var/www/html/wp-config.php
      - ./.env.local:/var/www/html/.env
      - ./docker-entrypoint.dev.sh:/usr/local/bin/docker-entrypoint.sh:ro
      - ./sitemap.xml:/var/www/html/sitemap.xml
      - ./uploads/:/var/www/html/wp-content/uploads/