version: "3.3"

# used for pipeline build
services:
  db: 
    image: flobbe9/${WORDPRESS_DB_NAME}
    build:
      context: .
      dockerfile: db.Dockerfile
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    ports:
      - ${WORDPRESS_DB_PORT}:${WORDPRESS_DB_PORT}
      
  wordpress:
    image: flobbe9/${NAME}
    depends_on: 
      - db
    build: 
      context: .
      args:
        - WORDPRESS_VERSION=${WORDPRESS_VERSION}
    environment:
      - WORDPRESS_DB_HOST=db
    ports: 
      - ${PORT}:80