version: "3.3"

# used for pipeline build
services:
  db: 
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${WORDPRESS_DB_PORT}:${WORDPRESS_DB_PORT}
      
  wordpress:
    image: flobbe9/${NAME}
    depends_on: 
      - db
    build: 
      context: .
      args:
        - WORDPRESS_VERSION=${WORDPRESS_VERSION}
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    ports: 
      - ${PORT}:80