<?php

/**
 * Modify <head> tags and response headers.
 */

/**
 * Add security related response headers.
 * 
 * @since latest
 */
function addSecurityResponseHeaders(): void {
    // https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CSP
    $defaultSrc = "default-src 'self' blob: 'unsafe-inline' 'unsafe-eval'";
    $imgSrc = "img-src * data: blob: 'unsafe-inline' 'unsafe-eval'";
    $fontSrc = "font-src 'self' data: 'unsafe-inline' 'unsafe-eval'";
    header("Content-Security-Policy: $defaultSrc; $imgSrc; $fontSrc");

    // https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Referrer-Policy
    header("Referrer-Policy: strict-origin-when-cross-origin");

    // https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Permissions-Policy
    header("Permissions-Policy: geolocation=(), midi=(), camera=(), usb=(), magnetometer=(), accelerometer=(), gyroscope=(), microphone=()");

    // https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Strict-Transport-Security
    header("Strict-Transport-Security: max-age=31536000; includeSubDomains");
}


/**
 * Modify headers that are generated by wordpress.
 * 
 * @author t.nghiem
 * @since latest
 */
function modifyAutoGeneratedHeaders(): void {
    // remove some <head> tags
    add_action('wp_head', 'ob_start', 1, 0);
    add_action('wp_head', function () {
        $pattern = '/.*' . preg_quote(esc_url(get_feed_link('comments_' . get_default_feed())), '/') . '.*[\r\n]+/';
        echo preg_replace($pattern, '', ob_get_clean());
    }, 3, 0);
    remove_action('wp_head', 'feed_links', 2);
    remove_action('wp_head', 'feed_links_extra', 3);
    remove_action('wp_head', 'wp_resource_hints', 2);
    remove_action('wp_head', 'wp_generator');
    remove_action('wp_head', 'rsd_link');
    remove_action('wp_head', 'wlwmanifest_link');
    remove_action('wp_head', 'adjacent_posts_rel_link_wp_head', 10);
    remove_action('wp_head', 'wp_generator');
    remove_action('wp_head', 'wp_shortlink_wp_head', 10);
    remove_action('wp_head', 'print_emoji_detection_script', 7);

    remove_action('admin_print_scripts', 'print_emoji_detection_script');
    remove_action('wp_print_styles', 'print_emoji_styles');
    remove_action('admin_print_styles', 'print_emoji_styles');
  
    remove_filter('the_content_feed', 'wp_staticize_emoji');
    remove_filter('comment_text_rss', 'wp_staticize_emoji');
    remove_filter('wp_mail', 'wp_staticize_emoji_for_email');
    add_filter('use_default_gallery_style', '__return_false');
    add_filter('emoji_svg_url', '__return_false');
    add_filter('show_recent_comments_widget_style', '__return_false');
    remove_action('wp_enqueue_scripts', 'gutenberg_common_scripts_and_styles'); 
}