name: spellbook_ug_wordpress main

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

        # TODO: run to test
     

  push_to_DockerHub:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        run: docker-compose build --build-arg WORDPRESS_DB_NAME=${{secrets.WORDPRESS_DB_NAME}} --build-arg WORDPRESS_DB_USER=${{secrets.WORDPRESS_DB_USER}} --build-arg WORDPRESS_DB_PASSWORD=${{secrets.WORDPRESS_DB_PASSWORD}} --build-arg MYSQL_ROOT_PASSWORD=${{secrets.MYSQL_ROOT_PASSWORD}}

      - name: Push images to Dockerhub
        run: docker-compose push