name: spellbook_gmbh_wordpress test

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches: 
      - dev

jobs:
  copy_stuff_to_remote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Get all files for remote server that have changed since last commit
        id: changed-remote-files
        uses: tj-actions/changed-files@v45
        with:
            # include_all_old_new_renamed_files: true
            since_last_remote_commit: true
            files: |
                remoteFiles/**
            separator: ","

      - name: Copy changed files to remote (if any)
        if: steps.changed-remote-files.outputs.any_changed == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
            host: spellbook-gmbh.de
            username: ${{ secrets.SSH_USER_NAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            source: ${{ steps.changed-remote-files.outputs.all_changed_files }}
            target: /root