name: spellbook_gmbh_wordpress main

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches: 
      - dev

jobs:
  deploy_to_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Copy file contents to temporary github env
        run: |
            echo DOCKER_ENTRYPOINT_SH="$(cat docker-entrypoint.sh)" >> $GITHUB_ENV
        shell: bash

      - uses: appleboy/ssh-action@v1.0.3
        with: 
          host: spellbook-gmbh.de
          username: ${{ secrets.SSH_USER_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          debug: true
          script: |
            ./copyFilesToRemote.sh test.sh "${{env.DOCKER_ENTRYPOINT_SH}}"