name: spellbook_gmbh_wordpress test

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches: 
      - dev

jobs:
  deploy_to_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Copy file contents to temporary github env
        uses: appleboy/scp-action@v0.1.7
        with:
            host: spellbook-gmbh.de
            username: ${{ secrets.SSH_USER_NAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            source: "docker-entrypoint.sh,test.sh"
            target: ./