name: spellbook_gmbh_wordpress dev

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      # this does not check container health
      # - name: Compose up
      #   uses: hoverkraft-tech/compose-action@v2.0.0
        # with: 
        #   compose-file: "./docker-compose.dev.yml"

      - name: move some config files to remote server
        run: | 
          yes |  sshpass -p '${{ secrets.SSH_PASSWORD }}' | scp ./docker-compose.prod.yml ${{ secrets.SSH_USER_NAME }}@spellbook-gmbh.de:~/docker-compose.yml