name: spellbook_gmbh_wordpress main

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Compose up
        run: docker compose -f 'docker-compose.pipeline.yml' up -d
        
        
  push_to_DockerHub:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4
  
      - name: move .env vars to temporary github env
        # NOTE: GITHUB_ENV vars are only accessible inside this job
        run: |
          echo $(cat .env | grep '^VERSION=.*$') >> $GITHUB_ENV
          echo $(cat .env | grep '^WORDPRESS_VERSION=.*$') >> $GITHUB_ENV
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Wordpress
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/spellbook_gmbh_wordpress:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/spellbook_gmbh_wordpress:${{env.VERSION}}
          build-args: |
            WORDPRESS_VERSION=${{env.WORDPRESS_VERSION}}
          

  deploy_to_server:
    runs-on: ubuntu-latest
    needs: push_to_DockerHub

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Copy some files to remote
        uses: appleboy/scp-action@v0.1.7
        with:
            host: spellbook-gmbh.de
            username: ${{ secrets.SSH_USER_NAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            source: copySecretsToRemote.sh,docker-entrypoint.sh,docker-compose.yml
            target: /root

      - name: copy .env vars to temporary github env
        run: |
            echo $(cat .env | grep '^MYSQL_VERSION=.*$') >> $GITHUB_ENV
        shell: bash

      - uses: appleboy/ssh-action@v1.0.3
        with: 
          host: spellbook-gmbh.de
          username: ${{ secrets.SSH_USER_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          debug: true
          script: |
            ./copySecretsToRemote.sh WORDPRESS_DB_NAME='${{secrets.WORDPRESS_DB_NAME}}' WORDPRESS_DB_USER='${{secrets.WORDPRESS_DB_USER}}' WORDPRESS_DB_PASSWORD='${{secrets.WORDPRESS_DB_PASSWORD}}' MYSQL_ROOT_PASSWORD='${{secrets.MYSQL_ROOT_PASSWORD}}' MYSQL_VERSION='${{env.MYSQL_VERSION}}'

            docker compose pull wordpress
            yes | docker rm $(docker container ls --all --filter=ancestor=$(docker images -f "dangling=true" -q) --format "{{.ID}}") --force
            yes | docker image rm $(docker images -f "dangling=true" -q)
            docker compose up wordpress -d