name: spellbook_ug_wordpress dev

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Compose up
        uses: hoverkraft-tech/compose-action@v2.0.0