name: spellbook_gmbh_wordpress test

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches: 
      - dev

jobs:
  copy_stuff_to_remote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Copy changed files to remote
        uses: appleboy/scp-action@v0.1.7
        with:
            host: spellbook-gmbh.de
            username: ${{ secrets.SSH_USER_NAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            source: remoteFiles/*
            target: /root