name: spellbook_gmbh_wordpress dev

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      # this does not check container health
      - name: Compose up
        run: docker-compose up -d --abort-on-container-exit
        # uses: hoverkraft-tech/compose-action@v2.0.0
        # with: 
        #   compose-file: "./docker-compose.dev.yml"
        